### ISSUE TITLE
advantages over crypto-browserify

### ISSUE THREAD

**Issue by kesla** [dominictarr/sodium-browserify#1]
Hey,

What's the advantage of using this compared to ctypto-browserify?

**Comment by dominictarr** [comment]
crypto-browserify is based on a previous generation of cryptography library - it's a polyfil for node's crypto lib, which is based on openssl. open ssl is based on a bunch of TLA standards which _all have bugs, or weird edge cases you must understand to use safely_. RSA, AES, SHA... all have problems(various). 

sodium is a fork of nacl, which is designed so that the cryptoprimitives simply do not have those problems.

I would recommend reading this paper: http://citeseer.ist.psu.edu/search?q=The+security+impact+of+a+new+cryptographic+library&submit=Search&sort=rlv&t=doc
